version: '3.8'

networks:
  backend:
    name: backendnet
    driver: bridge

services:
  lbdbphp:
    container_name: lbdbphp
    build:
      context: ./build/php/
    depends_on:
      - lbdbpostgres
    restart: on-failure
    volumes:
      - ./../app:/var/www/html
      - ./../app/var/cache:/var/www/html/var/cache:cached
      - ./../app/var/log:/var/www/html/var/log:cached
    networks:
      - backend
  lbdbnginx:
    container_name: lbdbnginx
    build:
      context: ./build/nginx/
    depends_on:
      - lbdbphp
    ports:
      - 8000:80
      - 8443:443
    restart: always
    volumes:
      - ./../app/:/var/www/html
      - ./../app/var/cache:/var/www/html/var/cache:cached
      - ./../app/var/log:/var/www/html/var/log:cached
      - ./build/nginx/logs/:/var/log/nginx
    networks:
      - backend
  lbdbpostgres:
    container_name: lbdbpostgres
    build:
      context: ./build/postgres/
    restart: always
    environment:
      POSTGRES_USER: lbdb_user
      POSTGRES_DB: lbdb_db
      POSTGRES_PASSWORD: lbdb_pass
    volumes:
      - ./build/postgres/data:/var/lib/postgres/data
    networks:
      - backend
  lbdbadminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
  lbdbredis:
    container_name: lbdbredis
    image: redis:alpine3.13
    networks:
      - backend
  lbdbrabbitmq:
    container_name: lbdbrabbitmq
    image: rabbitmq:3.8.11-alpine
    networks:
      - backend
